name: 52aa6377acf1-firestore-converter
on: [push]
env:
  WORKING_DIRECTORY: 52aa6377acf1-firestore-converter

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          yarn install
          yarn lint
