name: ceb0080d94f0-storybook-automatic-testing
on: [push]
env:
  WORKING_DIRECTORY: ceb0080d94f0-storybook-automatic-testing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          yarn install
          yarn lint
          yarn test
